force-app/main/default/objects/PurgeRecordScheduler__mdt/PurgeRecordScheduler__mdt.object-meta.xml
<CustomObject>
    <label>Purge Record Scheduler</label>
    <pluralLabel>Purge Records Scheduler</pluralLabel>
</CustomObject>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/PartialDelete__c.field-meta.xml
<CustomField>
    <fullName>PartialDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partial Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/QueryFilter__c.field-meta.xml
<CustomField>
    <fullName>QueryFilter__c</fullName>
    <inlineHelpText>This is very important and required, that filter which records should be deleted</inlineHelpText>
    <label>Query Filter</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/RunAtSystemLevel__c.field-meta.xml
<CustomField>
    <fullName>RunAtSystemLevel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run At System Level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/SendNotification__c.field-meta.xml
<CustomField>
    <fullName>SendNotification__c</fullName>
    <label>Send Notification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>If Errors</fullName>
            </value>
            <value>
                <fullName>If Success</fullName>
            </value>
            <value>
                <fullName>Always</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/sObjectName__c.field-meta.xml
<CustomField>
    <fullName>sObjectName__c</fullName>
    <label>sObject Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PurgeRecordBatchTest.cls
@istest
public class PurgeRecordBatchTest {
	@istest
    static void testPurgeEventLogLinkBatchTest() {
     
        PurgeRecordScheduler__mdt prs = new PurgeRecordScheduler__mdt();
        prs.sObjectName__c ='Account';
        prs.Active__c = true;
        prs.PartialDelete__c = false;
        prs.QueryFilter__c = ' name != \'1\' ';
        prs.RunAtSystemLevel__c = true;
        prs.SendNotification__c = 'Always';
        
        Test.startTest();
        PurgeRecordBatch b = new PurgeRecordBatch(prs);
        b.execute(null, null);
        Database.executeBatch(b, 10000);
        Test.stopTest();
    }
}