force-app/main/default/objects/PurgeRecordScheduler__mdt/PurgeRecordScheduler__mdt.object-meta.xml
<CustomObject>
    <label>Purge Record Scheduler</label>
    <pluralLabel>Purge Records Scheduler</pluralLabel>
</CustomObject>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/PartialDelete__c.field-meta.xml
<CustomField>
    <fullName>PartialDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partial Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/QueryFilter__c.field-meta.xml
<CustomField>
    <fullName>QueryFilter__c</fullName>
    <inlineHelpText>This is very important and required, that filter which records should be deleted</inlineHelpText>
    <label>Query Filter</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/RunAtSystemLevel__c.field-meta.xml
<CustomField>
    <fullName>RunAtSystemLevel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run At System Level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/SendNotification__c.field-meta.xml
<CustomField>
    <fullName>SendNotification__c</fullName>
    <label>Send Notification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>If Errors</fullName>
            </value>
            <value>
                <fullName>If Success</fullName>
            </value>
            <value>
                <fullName>Always</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurgeRecordScheduler__mdt/fields/sObjectName__c.field-meta.xml
<CustomField>
    <fullName>sObjectName__c</fullName>
    <label>sObject Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PurgeRecordSchedulerTest.cls
@isTest
public class PurgeRecordSchedulerTest {

    @isTest
    static void testConstructor() {
        // Simulando os dados de metadados personalizados
        PurgeRecordScheduler__mdt purgeRecordSetting = new PurgeRecordScheduler__mdt();
        purgeRecordSetting.sObjectName__c = 'Account';
        purgeRecordSetting.RunAtSystemLevel__c = false;
        purgeRecordSetting.QueryFilter__c = 'LastModifiedDate < LAST_N_DAYS:30';
        purgeRecordSetting.PartialDelete__c = false;
        purgeRecordSetting.SendNotification__c = 'Always';
        purgeRecordSetting.Active__c = true;
        
        PurgeRecordScheduler scheduler = new PurgeRecordScheduler(purgeRecordSetting);
        System.assertNotEquals(null, scheduler, 'o objeto deve ser criado');
    }
    
    @isTest
    static void testExecute() {
        // Simulando os dados de metadados personalizados
        PurgeRecordScheduler__mdt purgeRecordSetting = new PurgeRecordScheduler__mdt();
        purgeRecordSetting.sObjectName__c = 'Account';
        purgeRecordSetting.RunAtSystemLevel__c = false;
        purgeRecordSetting.QueryFilter__c = 'LastModifiedDate < LAST_N_DAYS:30';
        purgeRecordSetting.PartialDelete__c = false;
        purgeRecordSetting.SendNotification__c = 'Always';
        purgeRecordSetting.Active__c = true;
        
        PurgeRecordScheduler scheduler = new PurgeRecordScheduler(purgeRecordSetting);
        
        // Simulando o batch execution
        Test.startTest();
        // Executa o método execute
         scheduler.execute(null);
        Test.stopTest();
        //Verifica se um novo lote de exclusão de registros foi criado consultando a tabela AsyncApexJob do Salesforce
        Integer batchJobsCount = [SELECT count() FROM AsyncApexJob WHERE JobType = 'BatchApex' AND ApexClass.Name = 'PurgeRecordBatch'];
        System.assertNotEquals(0, batchJobsCount, 'Batch job not created');
        
        
    }
    
   
    @isTest
    static void testStartMethod() {
        // Cria uma lista simulada de PurgeRecordScheduler__mdt com valores fictícios
        List<PurgeRecordScheduler__mdt> mockSettingsList = new List<PurgeRecordScheduler__mdt>();
        PurgeRecordScheduler__mdt settings = (PurgeRecordScheduler__mdt) Type.forName('PurgeRecordScheduler__mdt').newInstance();
        settings.sObjectName__c = 'Account';
        settings.QueryFilter__c = 'CreatedDate = LAST_N_DAYS:30';
        settings.PartialDelete__c = false;
        settings.RunAtSystemLevel__c = true;
        settings.SendNotification__c = 'Always';
        settings.Active__c = true;
        mockSettingsList.add(settings);
 
        Test.startTest();
        // Chama o método start() da classe PurgeRecordScheduler com a lista simulada
        PurgeRecordScheduler.startTest(mockSettingsList);
        Test.stopTest();
        // Verifica se os agendamentos foram criados consultando a tabela CronTrigger do Salesforce
        Integer scheduledJobsCount = [SELECT count() FROM CronTrigger WHERE CronJobDetail.Name LIKE 'PurgeRecordScheduler%'];
        System.assertNotEquals(0, scheduledJobsCount, 'Scheduled jobs not created');
    }

    
    @isTest
    static void testAbort() {
        Test.startTest();
        PurgeRecordScheduler.abort();
        Test.stopTest();
        List<CronTrigger> scheduledJobs = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name LIKE 'PurgeRecordScheduler%'];
        System.assert(scheduledJobs.isEmpty(), 'Todas as tarefas devem ser abortadas');
        
    }


}